export const elementos = {
    containerMusicas: document.getElementById('container-musicas'),
    containerArtistas: document.getElementById('container-artistas'),
    containerPlaylists: document.getElementById('container-playlists'),
    listaPlaylists: document.getElementById('lista-playlists'),
    listaPlaylistsModal: document.getElementById('lista-playlists-modal'),
    btnNovaPlaylist: document.getElementById('btn-nova-playlist'),
    modalPlaylist: document.getElementById('modal-playlist'),
    modalAdicionarPlaylist: document.getElementById('modal-adicionar-playlist'),
    nomePlaylist: document.getElementById('nome-playlist'),
    salvarPlaylist: document.getElementById('salvar-playlist'),
    cancelarPlaylist: document.getElementById('cancelar-playlist'),
    fecharModal: document.getElementById('fechar-modal'),
    fecharModalAdicionar: document.getElementById('fechar-modal-adicionar'),
    cancelarAdicionar: document.getElementById('cancelar-adicionar'),
    musicaSelecionada: document.getElementById('musica-selecionada'),
    campoBusca: document.getElementById('campo-busca'),
    nomeMusicaAtual: document.getElementById('nome-musica-atual'),
    artistaMusicaAtual: document.getElementById('artista-musica-atual'),
    capaMusicaAtual: document.getElementById('capa-musica-atual'),
    btnPlay: document.getElementById('btn-play'),
    barraProgresso: document.getElementById('barra-progresso'),
    tempoAtual: document.getElementById('tempo-atual'),
    tempoTotal: document.getElementById('tempo-total')
};
